services:
  dev-db:
    image: postgres:15
    container_name: dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    expose:
      - "5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - lsib-network

  backend_nestjs:
    build: ./lsi-kintai-nestjs-backend
    container_name: backend_nestjs
    volumes:
      - ./lsi-kintai-nestjs-backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://devuser:devpass@dev-db:5432/devdb?schema=public"
      JWT_SECRET: "LSI_KINTAI_SECRET_KEY"
      JWT_EXPIRES_IN: "3600s"
      FRONTEND_URLS: "http://localhost:5001,http://192.168.3.4:5001,http://localhost"
      PORT: 4000
    expose:
      - "4000"
    networks:
      - lsib-network
    depends_on:
      - dev-db

  frontend_nextjs:
    build: ./lsi-kintai-nextjs-frontend
    container_name: frontend_nextjs
    volumes:
      - ./lsi-kintai-nextjs-frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost/api"
      IP_HOST_URL: "http://192.168.3.4:3000"
    expose:
      - "3000"
    networks:
      - lsib-network
    depends_on:
      - backend_nestjs

  nginx_proxy:
    image: nginx:alpine
    container_name: lsi-kintai-crimson-sun
    expose:
      - "5001"
    # ports:
    #   - "5001:5001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lsib-network
      - caddy-network
    depends_on:
      - frontend_nextjs
      - backend_nestjs

networks:
  lsib-network:
    driver: bridge
  caddy-network:
    external: true
    name: caddy-proxy-network
